# Generated by Django 5.1.6 on 2026-09-14 11:58

import apps.organizations.utils
import autoslug.fields
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('subdomain', models.CharField(max_length=63, unique=True, validators=[apps.organizations.utils.validate_subdomain])),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.organizations.utils.get_organization_media_path_prefix)),
                ('organization_type', models.CharField(choices=[('CHAMBER', 'Chamber'), ('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('LABORATORY', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('DIAGNOSTIC_CENTER', 'Diagnostic Center'), ('BLOOD_BANK', 'Blood Bank'), ('AMBULANCE_SERVICE', 'Ambulance Service'), ('HOMEOPATHY', 'Homeopathy'), ('AYURVEDIC', 'Ayurvedic'), ('DENTAL', 'Dental'), ('VETERINARY', 'Veterinary')], default='CHAMBER', max_length=25)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_organizations', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('site_title', models.CharField(default='Sebagriho - Connecting Doctors and Patients', max_length=255, verbose_name='Site Title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.organizations.utils.appearance_logo_upload_path)),
                ('fav_icon', models.ImageField(blank=True, null=True, upload_to=apps.organizations.utils.appearance_favicon_upload_path, verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#308e87', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#f39159', max_length=7, verbose_name='Secondary Color')),
                ('font_family', models.CharField(choices=[('ROBOTO', 'Roboto'), ('POPPINS', 'Poppins'), ('PLAYFAIR_DISPLAY', 'Playfair Display'), ('RALEWAY', 'Raleway'), ('SATISFY', 'Satisfy'), ('KARLA', 'Karla'), ('MONTSERRAT', 'Montserrat'), ('INTER', 'Inter'), ('CAVEAT', 'Caveat'), ('OPEN_SANS', 'Open Sans')], default='ROBOTO', max_length=64, verbose_name='Font Family')),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearance_settings', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Appearance Setting',
                'verbose_name_plural': 'Appearance Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_owner', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
                ('permissions', models.ManyToManyField(blank=True, related_name='organization_roles', to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_members', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, related_name='members', to='organizations.organizationrole')),
            ],
        ),
        migrations.AddConstraint(
            model_name='organizationrole',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_role_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_per_organization'),
        ),
    ]
