# Generated by Django 5.1.6 on 2026-09-14 11:58

import apps.homeopathy.utils
import autoslug.fields
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeopathicMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, help_text='Image of the medicine', null=True, upload_to=apps.homeopathy.utils.get_medicine_media_path_prefix)),
                ('name', models.CharField(max_length=100)),
                ('power', models.PositiveIntegerField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_homeopathic_patients_medicines', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeopathicPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.PositiveIntegerField(editable=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=apps.homeopathy.utils.get_homeopathic_patient_slug, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('old_serial_number', models.PositiveIntegerField(blank=True, null=True)),
                ('relative_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('miasm_type', models.CharField(blank=True, choices=[('ACUTE', 'Acute'), ('TYPHOID', 'Typhoid'), ('MALARIAL', 'Malarial'), ('RINGWORM', 'Ringworm'), ('PSORIC', 'Psoric'), ('SYCOTIC', 'Sycotic'), ('CANCER', 'Cancer'), ('TUBERCULAR', 'Tubercular'), ('LEPROSY', 'Leprosy'), ('SYPHILITIC', 'Syphilitic'), ('AIDS', 'AIDS')], max_length=20, null=True)),
                ('case_history', models.TextField(blank=True, null=True)),
                ('habits', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_homeopathic_patients', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeopathic_patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeopathicAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=apps.homeopathy.utils.get_homeopathic_appointment_slug, unique=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('treatment_effectiveness', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeopathic_appointments', to='organizations.organization')),
                ('homeopathic_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeopathic_patient_appointments', to='homeopathy.homeopathicpatient')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeopathicPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage', models.CharField(blank=True, help_text='e.g. 3 pills, 5 drops', max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, help_text='e.g. 3 times daily, once daily', max_length=100, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in days', null=True)),
                ('meal_timing', models.CharField(blank=True, choices=[('BEFORE_MEAL', 'Before Meal'), ('AFTER_MEAL', 'After Meal'), ('WITH_MEAL', 'With Meal'), ('BETWEEN_MEALS', 'Between Meals'), ('BEDTIME', 'At Bedtime'), ('EMPTY_STOMACH', 'On Empty Stomach'), ('ANY_TIME', 'Any Time')], max_length=20, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions', null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_prescription', to='homeopathy.homeopathicappointment')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_prescriptions', to='homeopathy.homeopathicmedicine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='homeopathicpatient',
            constraint=models.UniqueConstraint(fields=('organization', 'serial_number'), name='unique_patient_serial_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='homeopathicprescription',
            constraint=models.UniqueConstraint(fields=('appointment', 'medicine'), name='unique_medicine_per_appointment'),
        ),
    ]
