# Generated by Django 5.1.6 on 2026-09-17 11:50

import django.utils.timezone
from django.db import migrations, models


def assign_appointment_serial_numbers(apps, schema_editor):
    HomeopathicAppointment = apps.get_model("homeopathy", "HomeopathicAppointment")
    appointments = HomeopathicAppointment.objects.order_by(
        "organization_id",
        "appointment_date",
        "created_at",
        "pk",
    )

    current_group = None
    serial_number = 0
    for appointment in appointments.iterator():
        group = (appointment.organization_id, appointment.appointment_date)
        if group != current_group:
            current_group = group
            serial_number = 1
        else:
            serial_number += 1

        HomeopathicAppointment.objects.filter(pk=appointment.pk).update(
            serial_number=serial_number
        )


class Migration(migrations.Migration):

    dependencies = [
        ("homeopathy", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homeopathicappointment",
            options={"ordering": ["appointment_date", "serial_number"]},
        ),
        migrations.AddField(
            model_name="homeopathicappointment",
            name="appointment_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="homeopathicappointment",
            name="serial_number",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homeopathicappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("ABSENT", "Absent"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            assign_appointment_serial_numbers,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="homeopathicappointment",
            constraint=models.UniqueConstraint(
                fields=("organization", "appointment_date", "serial_number"),
                name="unique_appointment_serial_per_org_per_day",
            ),
        ),
    ]
