# Generated by Django 5.1.6 on 2026-09-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeopathy', '0002_alter_homeopathicappointment_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homeopathicappointment',
            name='unique_appointment_serial_per_org_per_day',
        ),
    ]
