# Generated by Django 5.1.6 on 2026-09-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeopathy', '0003_remove_homeopathicappointment_unique_appointment_serial_per_org_per_day'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='homeopathicappointment',
            constraint=models.UniqueConstraint(fields=('organization', 'appointment_date', 'serial_number'), name='unique_appointment_serial_per_org_per_day'),
        ),
    ]
